CREATE TABLE "lcn-watchdog_media_tracker" (
	"stock_id" integer,
	"timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"articles_positive_count" integer NOT NULL,
	"articles_negative_count" integer NOT NULL,
	"articles_neutral_count" integer NOT NULL,
	CONSTRAINT "lcn-watchdog_media_tracker_stock_id_timestamp_pk" PRIMARY KEY("stock_id","timestamp")
);
--> statement-breakpoint
CREATE TABLE "lcn-watchdog_tracked_stocks" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "lcn-watchdog_tracked_stocks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	CONSTRAINT "lcn-watchdog_tracked_stocks_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "lcn-watchdog_user_portfolio" (
	"user_id" varchar(255) NOT NULL,
	"stock_id" integer NOT NULL,
	"shares" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "lcn-watchdog_user_portfolio_user_id_stock_id_pk" PRIMARY KEY("user_id","stock_id")
);
--> statement-breakpoint
ALTER TABLE "lcn-watchdog_media_tracker" ADD CONSTRAINT "lcn-watchdog_media_tracker_stock_id_lcn-watchdog_tracked_stocks_id_fk" FOREIGN KEY ("stock_id") REFERENCES "public"."lcn-watchdog_tracked_stocks"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lcn-watchdog_user_portfolio" ADD CONSTRAINT "lcn-watchdog_user_portfolio_user_id_lcn-watchdog_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."lcn-watchdog_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lcn-watchdog_user_portfolio" ADD CONSTRAINT "lcn-watchdog_user_portfolio_stock_id_lcn-watchdog_tracked_stocks_id_fk" FOREIGN KEY ("stock_id") REFERENCES "public"."lcn-watchdog_tracked_stocks"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "name_idx" ON "lcn-watchdog_tracked_stocks" USING btree ("name");

--> insert data
INSERT INTO public."lcn-watchdog_tracked_stocks"(
	name)
	VALUES 
	('AMZN'),
	('AAPL'),
	('GOOGL'),
	('MSFT'),
	('TSLA');

INSERT INTO public."lcn-watchdog_media_tracker"(
	stock_id, articles_positive_count, articles_negative_count, articles_neutral_count)
	VALUES 
	(1, 22, 14, 7),
	(2, 22, 14, 7),
	(3, 10, 5, 4),
	(4, 12, 9, 5),
	(5, 18, 11, 7);